version: "3.7"

services:
  leetcode-dev:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ..:/home/docker-user/workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "2222:22"
    command: /bin/bash -c "sudo /usr/sbin/sshd -D -e -f /etc/ssh/sshd_config"

